# Generated by Django 2.1.5 on 2019-04-19 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_comment_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ReviewRating',
        ),
    ]
