# Generated by Django 2.1.5 on 2019-04-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190419_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='comment',
            new_name='review',
        ),
    ]
